apiVersion: v1
kind: Service
metadata:
  name: nextwork-flask-backend
  namespace: default
  labels:
    app: nextwork-flask-backend
spec:
  type: NodePort
  selector:
    app: nextwork-flask-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30080
  sessionAffinity: None
