apiVersion: v1
kind: Service
metadata:
  name: joke-generator
  namespace: default
  labels:
    app: joke-generator
spec:
  type: NodePort
  selector:
    app: joke-generator
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 30081
  sessionAffinity: None
